const express = require("express");
const morgan = require("morgan");
const path = require("path");
const ApiError = require("./Utility/ApiError");
const { errorController } = require("./Controller/errorController");
const bookingRouter = require("./Route/bookingRoute");
const viewRouter = require("./Route/viewRoute");
const reviewRouter = require("./Route/reviewRoute");
const venueRouter = require("./Route/houseRoute");
const userRouter = require("./Route/userRoute");
const app = express();
app.set("view engine", "pug");
app.set("views", path.join(__dirname, "views"));
app.use(express.static(path.join(__dirname, "public")));
app.use(express.json());
app.use(morgan("dev"));
app.use((req, res, next) => {
  console.log("you are in there");
  next();
});
app.use("/", viewRouter);
app.use("/api/v1/review", reviewRouter);
app.use("/api/v1/user", userRouter);
app.use("/api/v1/house", venueRouter);
app.use("/api/v1/bookings", bookingRouter);
app.use((req, res, next) => {
  next(new ApiError("no route like this", 400));
});
app.use(errorController);
module.exports = app;
